"""
Plain-language glossary for the Word documents (CLAUDE.md #19). Day 1 entries are ported from playground-dl/data/glossary.ts
(glossary_day1.json); entries added for later days are written here in the same shape: term, plain, example, from.
"""
import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
GLOSSARY = {k: {"term": v["term"], "plain": v["plain"], "example": v["example"] or "—", "from": v["from"] or "—"} for k, v in json.load(open(os.path.join(_HERE, "glossary_day1.json"), encoding="utf-8")).items()}


def G(key, term, plain, example="—", frm="—"):
    GLOSSARY[key] = {"term": term, "plain": plain, "example": example, "from": frm}


# ---- terms added while writing Day 1 documents
G("wireframe", "Wireframe", "A plain drawing of a screen's layout without colours or pictures. It shows what is on the screen and where, so that structure can be discussed before design.", "A grey box for the menu, a grey box for the lesson text, a grey box for the Next button.")
G("heuristic", "Heuristic", "A rule of thumb. A usability heuristic is a general rule, such as \"keep users informed about what is happening\", that experts use to check a screen quickly.", "Nielsen's list of ten usability heuristics.", "Nielsen 1994")
G("premortem", "Premortem", "A planning exercise: you imagine that the plan has failed a year from now and ask what went wrong. It brings risks to the surface before the money is spent.", "\"It is next March and the new course paths are not used. Why?\" Answer: nobody told the trainers.", "Klein 2007")
G("symptom", "Symptom and cause", "A symptom is what you can see or count (people leave). A cause is the reason behind it (they cannot find the next lesson). A number such as a drop-out rate shows the symptom, not the cause.", "40 of 100 learners leave is a symptom; \"the course has no path\" is a cause.")
G("dashboard", "Dashboard", "The first overview screen after login. On a learning platform it usually shows courses, progress and news.", "A start page with tiles for My courses, Certificates and News.")
G("badge", "Badge", "A small picture or title given to a learner for reaching something, such as finishing a course. A badge is a reward element from games.", "\"Finished: Contract Basics\".")
G("leaderboard", "Leaderboard", "A ranking of learners by points or activity. It rewards those who are already active and can discourage those at the bottom.", "A list of the ten most active learners this week.")
G("prioritisation-matrix", "Prioritisation matrix", "A table or chart that sets options against two or three criteria so that they can be compared side by side before choosing.", "Options in rows; user impact, effort and risk in columns.", "Gibbons 2018")
G("stakeholder", "Stakeholder", "A person or group that is affected by a decision or can influence it, such as management, trainers, learners or the customer's HR department.", "The head of HR who buys the courses for 200 employees.")
G("competitive-factor", "Competitive factor", "Something that makes customers choose one provider over another. For a learning platform, ease of use can be one.", "Two platforms offer the same course; learners and HR pick the one that is easier to use.")
G("e-learning", "E-learning platform", "Software on which people take courses online: it holds the lessons, tracks progress and often runs quizzes and certificates.", "A company LMS where staff take compliance training.")
G("lms", "LMS (learning management system)", "Software that an organisation uses to run online learning: it assigns courses, tracks who finished and issues reports.", "Moodle, or a company's own training portal.")


# ---- Day 2 · prototyping, testing, adaptive learning
G("prototype", "Prototype", "An early, simple version of a screen or a flow, made to test an idea before the real thing is built. It can be a paper sketch or a clickable mock-up.", "Six paper cards that show the course start; a learner points at what they would tap.", "Rettig 1994")
G("low-fi", "Low-fidelity and high-fidelity", "Low-fidelity means a rough, plain version (sketch, grey boxes). High-fidelity means a polished version that looks like the finished product. The lower the fidelity, the faster and cheaper it is to change.", "A grey-box wireframe of the learning path (low) against a fully coloured, clickable mock-up (high).", "Rettig 1994")
G("iterative", "Iterative design", "Designing in repeated rounds: make a small version, test it, improve it, test again. Each round is short, so mistakes are found while they are cheap to fix.", "Three one-week rounds on the course start screen instead of one six-month build.", "ISO 9241-210")
G("bml", "Build–Measure–Learn", "A loop from lean product development: build the smallest version that can be tested, measure what users do, and learn whether to keep, change or drop the idea.", "Build a clickable path, watch five learners use it, learn that nobody sees the Next button.", "Ries 2011")
G("think-aloud", "Think-aloud and task-based test", "In a task-based usability test the participant tries to complete a set task (for example \"find your next lesson\") while saying out loud what they think. You watch where they hesitate or fail.", "\"I would click Courses… no, that is a list… where is lesson 3?\"", "Nielsen 2000")
G("kpi", "KPI (key performance indicator)", "A number a team agrees to watch to judge whether something works, such as completion rate or time to finish a lesson. A good KPI has a baseline and a target.", "Completion rate of the first course: 58% today, goal 65% in six months.")
G("qualitative", "Qualitative and quantitative data", "Qualitative data says why: observations, quotes, interviews, usually from a few people. Quantitative data says how many or how much: counts, rates, times, usually from many people.", "Five learners say they miss a Next button (qualitative); 40% leave on lesson 3 (quantitative).")
G("adaptive", "Adaptive learning", "A learning system that changes what a learner sees, for example the next lesson or the difficulty, depending on what that learner does. The rules can be simple (if the test is passed, skip) or learned from data.", "A learner who passes the pre-test skips the basics unit.", "Kulik & Fletcher 2016")
G("recommendation", "Recommendation system", "Software that suggests the next item (a lesson, a course) from what a learner has done and what similar learners did. It needs data about many learners to work well.", "\"Learners like you went on to the unit on negotiation.\"")
G("learning-analytics", "Learning analytics", "Collecting and analysing data about learners and their context to understand and improve learning. In Europe this falls under data protection rules (DSGVO / GDPR), so it needs a legal basis and a clear purpose.", "A chart of how many learners leave at each lesson.", "GDPR")
G("personalisation", "Personalisation and transparency", "Personalisation shapes the platform to each learner. Transparency means the learner can see what the system does and why. The two can conflict: the more the system decides, the harder it is to explain.", "\"Suggested because you finished Unit 2 quickly.\"", "GDPR")
G("cold-start", "Cold start", "The problem that an adaptive or recommending system knows nothing about a new learner or a new course, so its first suggestions are weak until it has collected enough data.", "On day one of a new platform no one has finished anything, so there is nothing to learn from.")
G("over-engineering", "Over-engineering", "Building something more complex or more technical than the problem needs. A complex adaptive engine to fix a missing Next button is over-engineering.", "A neural network where a simple rule would do.")
G("ab-test", "A/B test and control group", "Two versions are shown to similar groups of users at the same time and the results are compared. The group that sees the old version is the control group. It shows whether a change made a difference.", "Half of new learners see the old start screen, half the new one; compare how many finish lesson 1.", "Kohavi et al. 2020")
G("stage-gate", "Stage gate", "A planned checkpoint between stages of an investment. Before the next stage gets money, a figure written down in advance must be met. If not, the stage is changed or stopped.", "Gate 1: at least 4 of 5 testers find the Next button in under 10 seconds.")
G("gdpr", "DSGVO (GDPR)", "The European data protection law (in English GDPR). It says when personal data may be collected and used, requires a clear purpose and, for tracking and profiling, often consent. It matters for learning analytics and adaptive systems.", "A recommendation engine that profiles learners needs a legal basis.", "Regulation (EU) 2016/679")
G("ai-act", "EU AI Act", "A European law that sorts AI systems by risk and sets rules for each class. AI that evaluates learning outcomes or steers the learning process is treated as high-risk in education. Obligations come into force in stages: check the dates.", "A system that decides which learners may continue a course.", "Regulation (EU) 2024/1689")
G("mvp", "Pilot", "A small, time-limited trial of a change with a few users, run to learn before a full roll-out.", "One course for eight weeks with 30 learners.")


# ---- Day 3 · learning psychology and cognitive load
G("working-memory", "Working memory", "The small mental workspace in which a person holds and works on information for a few seconds. It is very limited: current estimates for new material are about four chunks at a time.", "Remembering a phone number just long enough to dial it.", "Cowan 2001")
G("long-term-memory", "Long-term memory", "The store in which understood and practised knowledge is kept for days, months or years. Content gets there when it is understood, linked to what is known, and revisited.", "A skill you can still use a year after the course.", "Atkinson & Shiffrin 1968")
G("chunking", "Chunking", "Grouping several items into one meaningful unit so that working memory has less to hold. Twelve loose items become three groups of four.", "A phone number written as 0151 234 5678 instead of eleven separate digits.", "Miller 1956")
G("intrinsic", "Intrinsic load", "The mental effort that comes from the subject itself: how many new ideas there are and how much they depend on each other. Design cannot remove it, only order it sensibly.", "Learning data-protection law is harder than learning how to log in.", "Sweller et al. 1998")
G("extraneous", "Extraneous load", "Mental effort that is caused by poor presentation and does not help learning: clutter, a wall of text, unclear structure, unexplained terms. This is the load that UX can and should cut.", "Searching a long page for the one sentence that matters.", "Sweller et al. 1998")
G("germane", "Germane load", "Mental effort that goes into making sense of the content: linking ideas, working an example, explaining it to oneself. It is the effort you want to leave room for. The idea is still discussed by researchers; for design the useful split is effort that helps learning against effort that does not.", "Trying to apply a rule to a new case.", "Sweller et al. 1998")
G("visual-hierarchy", "Visual hierarchy", "Using size, colour, contrast and position so that the most important thing on a screen is seen first and the least important last. It controls where attention goes.", "A large heading, a normal paragraph, a small footnote.")
G("multimedia", "Multimedia principle", "People tend to learn better from words and pictures together than from words alone, provided the picture is relevant and placed close to the words it explains.", "A diagram with its labels inside it instead of a paragraph describing the same flow.", "Mayer 2009")
G("seductive", "Seductive details", "Interesting but irrelevant additions to a lesson (a funny picture, a side story). Studies found that they can distract from the main point and lower learning.", "A decorative photo of a pirate ship in a lesson on invoices.", "Harp & Mayer 1998")
G("expertise-reversal", "Expertise reversal", "Guidance and simplification that help beginners can get in the way of experts, who already have the knowledge and find the extra support redundant.", "Step-by-step hints that slow down a specialist.", "Kalyuga et al. 2003")
G("retrieval", "Retrieval practice and spacing", "Retrieval practice means trying to recall something instead of re-reading it. Spacing means revisiting it after a delay instead of all at once. Both strengthen long-term memory.", "A short quiz at the start of next week's lesson on this week's content.", "Roediger & Karpicke 2006")
G("microlearning", "Microlearning", "Learning in short, focused units of a few minutes, each with one goal. It fits the limited capacity of working memory and the time that working adults have.", "A six-minute unit with one learning goal and one check.")
G("learning-effective", "Learning-effective UX", "A design that helps learners reach the intended learning result at reasonable mental cost, not one that merely looks simple. It is judged by what learners understand and can do afterwards.", "A lesson after which five beginners can explain the key point in their own words.")


# ---- Day 4 · motivation, design principles, evaluation
G("intrinsic-motivation", "Intrinsic and extrinsic motivation", "Intrinsic motivation comes from the activity itself: interest, curiosity, the wish to get better. Extrinsic motivation comes from outside: points, money, a deadline, a certificate. Both exist; designs differ in which they lean on.", "Studying contracts because you want to understand them (intrinsic) or to get the certificate (extrinsic).", "Ryan & Deci 2000")
G("sdt", "Self-Determination Theory (SDT)", "A theory of motivation by Deci and Ryan. It says that people stay motivated when three needs are met: autonomy (I choose), competence (I can see I am getting better) and relatedness (I belong).", "A learner can pick the order of units (autonomy), sees skills gained (competence) and a study group (relatedness).", "Ryan & Deci 2000")
G("overjustification", "Overjustification effect", "When a reward is expected for something a person already enjoys, the person may come to see the reward as the reason and lose interest once it stops.", "A learner who liked quizzes starts only for points and stops when the points end.", "Deci, Koestner & Ryan 1999")
G("fogg", "Fogg Behavior Model", "A model that says a behaviour happens when motivation, ability and a prompt come together at the same moment. Raising motivation alone does not help if the step is hard or nobody prompts it.", "A reminder (prompt) that opens a three-minute task (ability) for a learner who wants to finish (motivation).", "Fogg 2009")
G("flow", "Challenge and skill balance (flow)", "People engage most when a task is neither too easy (boring) nor too hard (frustrating) for their current skill. Good learning design keeps the challenge just above the learner's level.", "A quiz that gets slightly harder as the learner succeeds.", "Csikszentmihalyi 1990")
G("goal-setting", "Clear goals", "Specific goals, stated up front, help people focus effort and judge their progress. In learning, that means saying what the learner will be able to do after a unit.", "\"After this unit you can write a counter-offer.\"", "Locke & Latham 2002")
G("goal-gradient", "Goal-gradient and endowed progress", "People work harder the closer they get to a goal (goal gradient), and they are more likely to continue when they already see some progress (endowed progress). A progress display uses both, but it must be honest.", "A bar that starts at 10% after registration because the first step is done.", "Kivetz et al. 2006; Nunes & Drèze 2006")
G("reinforcement", "Feedback and reinforcement", "Feedback tells a learner how they did and what to do next; reinforcement makes a helpful behaviour more likely to be repeated. Good feedback answers three questions: where am I going, how am I going, where to next.", "\"4 of 5 correct. Review question 2.\"", "Hattie & Timperley 2007")
G("dark-pattern", "Dark pattern and manipulation", "A design that pushes users to act against their own interest, for example by pressure, guilt or hidden costs. In learning, loss messages such as \"you will lose your streak\" can cross from motivation into manipulation.", "A pop-up that scolds the learner for missing a day.", "Gray et al. 2018")
G("perverse-incentive", "Perverse incentive", "An incentive that produces the opposite of what was intended: learners collect points by clicking quickly through lessons instead of learning.", "A badge for opening 10 lessons leads to opening lessons without reading them.")
G("hypothesis", "Hypothesis-based approach", "Writing down what you expect before you change something: \"We believe that X will lead to Y; we will know when Z moves.\" It makes the result checkable.", "\"We believe a next-step button will raise the 7-day return rate by five points.\"", "Gothelf & Seiden 2013")
G("activation", "Activation", "Getting the learner to do something with the content (answer, choose, try) instead of only reading or watching.", "A three-minute task after each unit.")
G("return-rate", "Return rate", "The share of learners who come back within a set time, for example within seven days. It is a simple sign of retention.", "62 of 100 new learners return within a week.")


# ---- Day 5 · user-centred UX design
G("feature-driven", "Feature-driven and user-driven", "Feature-driven means deciding what to build from what the software could do or what a department asked for. User-driven means deciding from what users need to do. A feature-driven platform grows long menus; a user-driven one grows paths.", "A new \"Social Feed\" nobody asked for, against a \"Continue\" button learners asked for.", "ISO 9241-210")
G("context-of-use", "Context of use", "The situation in which a product is used: who the users are, what goals and tasks they have, what device they use and where they are. Usability is always judged in a context.", "A learner on a phone in a train with ten minutes, against a learner at a desk for a whole day.", "ISO 9241-11")
G("contextual-inquiry", "Contextual inquiry and observation", "Watching and asking people at the place where they actually use a product, to see what they do rather than only what they say.", "Sitting next to an employee as they try to find their training on a Monday morning.", "Beyer & Holtzblatt 2017")
G("say-do", "Say-do gap", "People often do not do what they say they do or would do. So user research should watch behaviour as well as ask opinions.", "Learners say they want more features, but they never open the ones that exist.", "Nielsen 2001")
G("kano", "Kano model", "A model that sorts product qualities into must-be (expected, only noticed when missing), one-dimensional (more is better) and attractive (a pleasant surprise). It shows why extra features do not make up for a failing basic.", "Finding your course is a must-be; a fun badge is attractive but cannot make up for not finding the course.", "Kano et al. 1984")
G("feature-creep", "Feature creep", "The slow growth of a product by adding more and more features until it is hard to use. Norman calls it creeping featurism.", "Twenty-two menu entries because every department got one.", "Norman 2013")
G("nps", "NPS (Net Promoter Score)", "A satisfaction number based on one question: how likely are you to recommend us? Answers from 0 to 10 are grouped into promoters, passives and detractors. It is widely used by management; critics say a single number hides the reasons.", "NPS of +20 means more promoters than detractors.", "Reichheld 2003")
G("persona", "Persona", "A made-up but data-based person who stands for a group of users, with goals, problems and a situation. It makes the needs of a group easy to discuss. (Day 6 covers it in detail.)", "\"Mia, 38, project manager, ten minutes between meetings.\"", "Cooper 1999")
G("journey", "User journey", "A step-by-step picture of what a user does, thinks and feels from the first contact to the goal. It shows where the experience breaks. (Day 6 covers it in detail.)", "Search, enrol, start lesson 1, stop at lesson 3.", "Kalbach 2020")


# ---- Day 6 · personas and user journeys
G("proto-persona", "Proto-persona", "A first persona written from the team's assumptions, before there is research. It is a hypothesis to be tested with real users, and must be labelled as such.", "\"We assume our main learner is a busy professional; we will check this with five interviews.\"", "Gothelf & Seiden 2013")
G("pain-point", "Pain point", "A place in the user's path where something goes wrong or is frustrating: they get stuck, lose time or give up.", "Not finding where you stopped after a three-day break.", "Gibbons 2018")
G("touchpoint", "Touchpoint", "Any contact between a user and the product or company: a screen, an email, a reminder, a report, a phone call.", "The reminder email at 08:00.", "Kalbach 2020")
G("segment", "User segment and segmentation", "A group of users who share needs or behaviour and differ from other groups. Segmentation splits users into such groups so that decisions can be made for each. Behaviour and goals work better than age or job title.", "Time-poor learners on phones against exam preparers on laptops.", "Pruitt & Grudin 2003")
G("emotion-curve", "Emotion curve", "A line in a journey map that shows how the user feels at each step, from frustrated to motivated. Low points show where to act first.", "The dip when the learner cannot find where they stopped.", "Gibbons 2018")
G("peak-end", "Peak-end rule", "People judge an experience mostly by its most intense moment and by how it ended, not by the average. For a course the last step matters.", "A smooth certificate step can colour the memory of a bumpy course.", "Kahneman et al. 1993")
G("primary-persona", "Primary and secondary persona", "The primary persona is the one whose needs the design must satisfy first. Secondary personas are served as long as that does not harm the primary one.", "Time-poor learners as primary, teachers as secondary.", "Cooper 1999")
G("business-critical", "Business-critical segment", "A segment whose behaviour decides the company's results, even if it is small, for example the training managers who decide whether a contract is renewed.", "60 training managers who renew licences for 5,000 learners.")
G("onboarding", "Onboarding", "The first steps a new user takes on a platform: signing up, finding a first course, getting the first result. A good start makes it likely that the learner carries on.", "A welcome screen that offers one first course and shows how long it takes.")


# ---- Day 7 · accessibility and inclusive design
G("accessibility", "Accessibility", "Making sure people with a wide range of abilities can perceive, use and understand a product: people who cannot see, hear, use a mouse or process complex text easily. Usability asks whether a user can reach a goal; accessibility asks whether everyone can get in.", "A learner who uses only the keyboard can finish the course.", "WCAG 2.2")
G("inclusive-design", "Inclusive design", "Designing so that as many people as possible can use a product, by thinking about differences from the start (permanent, temporary and situational limits) instead of adding fixes at the end.", "Captions help a deaf learner, and also a learner in a noisy train.", "Microsoft 2016")
G("persona-spectrum", "Persona spectrum", "A way of seeing that a limit can be permanent (one arm), temporary (a broken arm) or situational (holding a child). Designing for the permanent case often helps the other two.", "A one-handed design helps a parent holding a baby.", "Microsoft 2016")
G("wcag", "WCAG (Web Content Accessibility Guidelines)", "The international technical guidelines for accessible web content, by the W3C. WCAG 2.2 has 86 success criteria at levels A, AA and AAA, grouped under four principles: perceivable, operable, understandable, robust.", "Success criterion 1.4.3: text needs a contrast of at least 4.5 : 1 against its background.", "W3C 2023")
G("pour", "POUR (the four WCAG principles)", "Perceivable (people can see or hear it), Operable (people can use it), Understandable (people can follow it) and Robust (it works with assistive technology).", "Captions make a video perceivable; keyboard access makes a quiz operable.", "WCAG 2.2")
G("conformance", "Conformance levels A, AA, AAA", "WCAG success criteria are rated A (essential), AA (the usual legal and practical target) and AAA (the highest, not always possible for all content).", "A public service is usually asked to meet Level AA.", "WCAG 2.2")
G("contrast", "Contrast ratio", "How much a text colour differs in brightness from its background, written as a ratio such as 4.5 : 1. WCAG AA asks for at least 4.5 : 1 for normal text and 3 : 1 for large text.", "Light grey text on white may only reach 2.3 : 1 and fails.", "WCAG 2.2, 1.4.3")
G("screen-reader", "Screen reader and assistive technology", "A screen reader reads a page aloud or in Braille. Assistive technology means any tool that helps a person use a computer: screen readers, magnifiers, switches, voice control. A page must give these tools the right names, roles and states.", "A button that the screen reader announces as \"unlabelled button\" cannot be used.", "WCAG 2.2")
G("keyboard", "Keyboard operability", "Everything that can be done with a mouse can also be done with the keyboard alone, in a sensible order, with a visible focus. People who cannot use a mouse depend on it.", "A quiz that can only be answered by dragging fails this.", "WCAG 2.2, 2.1.1")
G("aria", "ARIA", "A set of attributes (WAI-ARIA) that tell assistive technology what a custom control is and does. The first rule: where a native HTML element does the job, use it instead of adding ARIA.", "Use a real button, not a clickable box labelled with ARIA.", "W3C")
G("plain-language", "Plain language (Einfache Sprache, Leichte Sprache)", "Clear, short, everyday wording. In German there are two forms: Einfache Sprache (simple language, fewer rules) and Leichte Sprache (easy-to-read language with strict rules, for people with learning difficulties). Day 14 covers it in detail.", "\"When you finish, upload your answers.\"", "BITV 2.0")
G("udl", "Universal Design for Learning (UDL)", "A framework that asks designers to offer several means of engagement (why), representation (what) and action and expression (how), so that learners can reach the goal in different ways.", "The same unit as text, as a captioned video and as audio.", "CAST 2024")
G("bfsg", "BFSG, EN 301 549, BITV 2.0", "BFSG is the German law (Barrierefreiheitsstärkungsgesetz) that applies the European Accessibility Act, from 28 June 2025, to many consumer-facing digital services. EN 301 549 is the European standard that refers to WCAG for web content. BITV 2.0 covers the web offers of public bodies. Scope and exemptions are in flux: check them.", "A public university and an online shop meet different rules.", "Directive (EU) 2019/882")
G("overlay", "Accessibility overlay", "A third-party toolbar added on top of a site that promises to fix accessibility problems automatically. Many accessibility experts advise that it does not fix the underlying problems, which must be solved in the content and the code.", "A widget that claims to make the whole site compliant in a day.")
G("audit", "Accessibility audit and automated check", "An audit checks a product against criteria such as WCAG, by tools and by hand (keyboard, screen reader). Automated tools find only part of the problems, so they are a start, not proof.", "An automated check passes; a manual test finds a quiz that cannot be operated by keyboard.", "WCAG 2.2")
G("sus", "SUS (System Usability Scale)", "A ten-question questionnaire that gives a usability score from 0 to 100. It can be asked of each user group to compare them.", "Group A scores 78, group B scores 52: group B has a problem.", "Brooke 1996")


# ---- Day 8 · structure, visual hierarchy, interaction
G("ia", "Information architecture (IA)", "How the content and functions of a platform are organised, grouped and named so that people can find them. It covers organisation, labelling, navigation and search.", "Four sections named Learn, Find, Progress, Help and account.", "Rosenfeld et al. 2015")
G("navigation", "Navigation", "The ways a user moves through a platform: menus, links, buttons, a path above the page, a Next link. Good navigation shows where you are and where you can go.", "A path such as Learn › Negotiation › Lesson 3.", "Rosenfeld et al. 2015")
G("card-sort", "Card sorting and tree testing", "In a card sort, people group labelled cards into the categories that make sense to them; in a tree test, they try to find items in a text-only version of the menu. Both check an information architecture before it is built.", "Ten learners sort 12 cards into four sections.", "Spencer 2009")
G("hierarchy", "Hierarchy (structure and visual)", "A structural hierarchy ranks content from main sections to details. A visual hierarchy uses size, colour, contrast and position so that the most important thing is seen first.", "A large heading, a main button, then quieter links.", "Wertheimer 1923")
G("gestalt", "Gestalt principles", "Rules of how people group what they see: things that are close (proximity) or alike (similarity) are seen as belonging together, and a line or flow (continuity) is followed. Designers use them to group without boxes.", "Three buttons close together read as one group.", "Wertheimer 1923")
G("cta", "Call to action (CTA)", "The button or link that invites the user to take the main next step, such as Start lesson or Continue. A screen should have one main call to action, clearly stronger than the rest.", "A filled blue Continue button and two quiet text links.", "Shneiderman et al. 2016")
G("affordance", "Affordance and signifier", "An affordance is what an object allows you to do; a signifier is a sign that shows it. A button that looks pressable signals that it can be pressed.", "A raised, labelled button signals Press me.", "Norman 2013")
G("hick", "Hick's law", "The more choices a person has, the longer it takes to decide. Designers use it to keep the number of options at a decision point small.", "Five main menu entries are quicker to scan than thirty.", "Hick 1952")
G("fitts", "Fitts's law", "The time to reach a target depends on how far away it is and how big it is. Important targets should be large and close to where the user's attention is.", "A big Continue button is easier to tap than a small icon.", "Fitts 1954")
G("consistency", "Consistency", "The same thing looks and works the same way everywhere, so that what a user learns on one screen holds on the next. It is one of Nielsen's usability heuristics.", "Every primary button is blue and in the same place.", "Nielsen 1994")
G("progressive-disclosure", "Progressive disclosure", "Showing only what is needed now and revealing advanced options on request, so that the first view stays simple.", "An advanced settings area behind a More link.", "Nielsen 2006")
G("style-guide", "Design system and style guide", "A shared set of components, colours, fonts and rules (a design system) with a written guide, so that every screen is built the same way.", "One button style used on every page.")
